-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.tweets
(
    tweet_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    message text COLLATE pg_catalog."default" NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT tweets_pkey PRIMARY KEY (tweet_id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tweets
    OWNER to postgres;

GRANT ALL ON TABLE public.tweets TO anon;

GRANT ALL ON TABLE public.tweets TO authenticated;

GRANT ALL ON TABLE public.tweets TO postgres;

GRANT ALL ON TABLE public.tweets TO service_role;
