-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.append_to_replies(
	add_replies_to uuid,
	replied_tweet_id uuid)
    RETURNS void
    LANGUAGE 'sql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
    update tweets
    set replies = replies || replied_tweet_id
    where tweets.tweet_id = add_replies_to
  
$BODY$;

ALTER FUNCTION public.append_to_replies(uuid, uuid)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.append_to_replies(uuid, uuid) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.append_to_replies(uuid, uuid) TO anon;

GRANT EXECUTE ON FUNCTION public.append_to_replies(uuid, uuid) TO authenticated;

GRANT EXECUTE ON FUNCTION public.append_to_replies(uuid, uuid) TO postgres;

GRANT EXECUTE ON FUNCTION public.append_to_replies(uuid, uuid) TO service_role;
