-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.user_bookmarked_tweet
(
    user_id uuid NOT NULL,
    tweet_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_bookmarked_tweet_pkey PRIMARY KEY (user_id, tweet_id),
    CONSTRAINT fk_tweet_id FOREIGN KEY (tweet_id)
        REFERENCES public.tweets (tweet_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_user_id FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_bookmarked_tweet
    OWNER to postgres;

GRANT ALL ON TABLE public.user_bookmarked_tweet TO anon;

GRANT ALL ON TABLE public.user_bookmarked_tweet TO authenticated;

GRANT ALL ON TABLE public.user_bookmarked_tweet TO postgres;

GRANT ALL ON TABLE public.user_bookmarked_tweet TO service_role;
